# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  push_current_lineup_job:
    class: PushCurrentLineupJob
    schedule: every hour
  drain_hooks_job:
    class: DrainHooksJob
    schedule: every day at 3am in UTC
  crawl_artworks_job:
    class: CrawlArtworksJob
    schedule: every day at 4am in UTC
  manage_apache_log_data_job:
    class: ManageApacheLogDataJob
    schedule: every day at 5am in UTC
  ensure_current_lineup_job:
    class: EnsureCurrentLineupJob
    schedule: every day at 6am in UTC
  produce_daily_packet_job:
    class: ProduceDailyPacketJob
    schedule: every day at 7am in UTC
